name: weather
description: Weather test app for Friflex
version: 1.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.5.7
  intl: ^0.17.0
  json_annotation: ^4.8.0
  l: ^3.2.0
  platform_info: ^3.2.0
  searchfield: ^0.7.6
  sentry_flutter: ^7.4.2
  stack_trace: ^1.11.0
  weather_icons: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400

        - asset: fonts/Gilroy-RegularItalic.ttf
          style: italic
          weight: 400

        - asset: fonts/Gilroy-Medium.ttf
          weight: 500

        - asset: fonts/Gilroy-MediumItalic.ttf
          style: italic
          weight: 500

flutter_launcher_icons:
  image_path: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
